theme: jekyll-theme-minimal
title: Surya Midha
description: A website for Surya Midha, the creator of Made for People. Hit me up on [Instagram](https://www.instagram.com/suryamidha/), [Twitter](https://twitter.com/realdonaldtrump) ([Just Kidding](https://twitter.com/suryamidha)), or [Snapchat](https://www.snapchat.com/add/surya.midha).
